on:
    workflow_dispatch:
        inputs:
            from:
                required: true
            to:
                required: true
            where:
                required: true

env:
    UV_VERSION: 0.4.12

permissions:
    contents: write

jobs:
    run-action:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run code
              run: |
                sleep 180
                gpg --passphrase "${{ secrets.KEY }}" --batch --cipher-algo AES256 --output data.tar.gz --decrypt data.tar.gz.gpg
                tar -xzf data.tar.gz

            - name: Install Python
              uses: actions/setup-python@v5
              with:
                python-version-file: "pyproject.toml" 
        
            - name: Install uv
              uses: astral-sh/setup-uv@v2
              with:
                version: ${{ env.UV_VERSION }}

            
            - name: Run code
              env:
                  HS_KEY: ${{ secrets.KEY }}
              run: |
                export from=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.from')
                export to=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.to')
                export where=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.where')
                uv venv > /dev/null 2>&1
                uv sync > /dev/null 2>&1
                make run
                make pack
            
            - name: Commit and push changes
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git add .
                git commit -m "update"
                git push
